# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/data/mongo-data:/data/db"
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/data/redis:/data"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
