# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: docker.io/mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    restart: always

  mongo-express:
    image: docker.io/mongo-express
    restart: always
    ports:
      - "8081:8081"
